### ISSUE TITLE
DRUP-735 apigee_auth key does not validate credentials

### ISSUE THREAD

**Issue by shadcn** [apigee/apigee-edge-drupal#178]
| Q                           | A
| --------------------------- | -----------------------------------------------
| Bug?                        | yes
| New Feature?                | no
| Module Version              | `8.x-1.x`
| PHP Client version          | `2.0.1`
| Requires PHP client fix     | no

#### Actual Behavior

Credentials submitted via the _admin/config/system/keys/manage/apigee_edge_connection_default_ are not validated against Apigee connection.

#### Expected Behavior

The connection for credentials provided should be validated.

#### Steps to Reproduce the behavior

1. Edit the auth key at _admin/config/system/keys/manage/apigee_edge_connection_default_
2. Select Configuration as the key provider.
3. Enter any random values.
4. Save.

The random values are saved.

#### Proposed Solution

Extend `\Drupal\apigee_edge\Plugin\KeyType\ApigeeAuthKeyType::validateKeyValue` to validate values provided for the key. Maybe extract `\Drupal\apigee_edge\Form\AuthenticationForm::validateForm` somewhere and reuse?

**Comment by mxr576** [comment]
@arshad This works are expected, only Apigee prefixed key providers can do validation on the Key form because they are defined by the Apigee Edge module. Others can only validate on the Authentication form, which is the main configuration page for Apigee Edge authentication set up.

So you can change the Key provider on the Key configuration form to anything but then you have to go back the Authentication form to Send a request if the Key provider is not an Apigee prefixed one.

**Comment by shadcn** [comment]
@mxr576 Sorry I don't follow.

`apigee_auth` is shipped with the Apigee Edge module. Can't we check if the values provided are valid credentials in `\Drupal\apigee_edge\Plugin\KeyType\ApigeeAuthKeyType::validateKeyValue`?

We are already doing some missing and empty field validations in there.

**Comment by mxr576** [comment]
Yeah, I did some digging as well since my comment and I'll look into this whether it is possible to do that there. My gut says Peter must have had a reason for not doing this validation there but we'll see.

**Comment by mxr576** [comment]
Okay, so probably the reason why Peter did not use this `validateKeyValue()` because it does not get called on the Authentication form. The reason for that is how the Key module's entity edit form got "included" in the Authentication form. Basically, it is a copy-paste from the Key module and it tries to replicate what Key module does when it processes a form and saves the submitted values. Calling validateKeyValue() is missing from the replicated behavior.

The way how this form was implemented originally in #103 caused way too many problems for us in the past. We tried to improve that implementation without rebuilding the form (#152) but this issue and #176 are the perfect examples that it is impossible to maintain the current solution.

In my PR, I'll try to expose a customized version of the KeyEditForm form on the AuthenticationForm which is something similar that I suggested when #103 was in progress.

**Comment by Jaesin** [comment]
Can't we just add the validation call to resolve this?

**Comment by mxr576** [comment]
We can and wait for the next issue to occur... it could happen that Key module will add extra steps to Key creation/update process that we won't even notice because of the current implementation. 
Also, if we would just add the missing validation callback to the Authentication form then Key's own add/edit form would not validate the provided credentials still. (Which is the original issue is about.)

**Comment by mxr576** [comment]
Okay, it seems my idea is working, we can even expose the key provider configuration as an "Advanced settings" on the Authentication form so we can reduce the navigation hell between the Authentication form and the Key edit form.

![image](https://user-images.githubusercontent.com/1755573/56208466-80247080-6051-11e9-856d-e8d1bbe67c85.png)

![image](https://user-images.githubusercontent.com/1755573/56208553-b5c95980-6051-11e9-947d-9022dcf8c9e3.png)

**Comment by shadcn** [comment]
This is now fixed in https://github.com/apigee/apigee-edge-drupal/pull/179
