### ISSUE TITLE
Add Edge role creation script to module

### ISSUE THREAD

**Issue by cnovak** [apigee/apigee-edge-drupal#210]
Currently the [module's documentation installation steps](https://www.drupal.org/docs/8/modules/apigee-edge/configure-the-connection-to-apigee-edge#assigning-the-developer-administrator-role) say to download a gist from my GitHub repo, which is weird.  This should be instead a script in the module.

**Comment by mxr576** [comment]
Well, it definitely seems odd that a customer has to pull down a script from your GH repo and not from an official Apigee repo, so one obvious solution for this problem is to move the _shell_ script to an official Apigee repo. What this script is needed for is only a one-time configuration.

IIRC I haven't seen any Drupal module yet that would ship a shell script as part of the module. Although it seems Drupal core's [.htaccess ](https://github.com/drupal/drupal/blob/8.7.x/.htaccess#L6) could handle it, if you would like to move it to the module I would suggest to rewrite the shell script to a Drush/Drupal Console command.
Your shell script obviously only runs on Unix based OS-es and Windows 10 with WSL enabled and it requires curl, but it does not validate whether it is installed or not.
The Drush/Drupal console command could run on all OS-es and because `ext-curl` is a requirement of Drupal (also Guzzle 6 is available) you would not need to worry about dependency issues and you could simplify your script a lot.

**Comment by cnovak** [comment]
Good input @mxr576 , was thinking that it would be good to move to module and later move into Drush/Drupal console, but the OS dependency would be good to solve ASAP.

**Comment by mxr576** [comment]
Not sure how else you could solve the OS dependency than the suggested solution. Probably you could to create a CMD or Powershell version from your script, but if you invest time to that, why do not you rather invest time to the cross-platform Drush/Drupal console command instead?
If you do not have the capacity to write the hybrid Drush/Drupal console command just let me and @arunz6161 know and we'll figure something out.
