### ISSUE TITLE
When clicking a link to view a "Team" entity, "Team Apps" should be shown, instead of "View"...

### ISSUE THREAD

**Issue by jacine** [apigee/apigee-edge-drupal#219]
Per discussions stemming from UX designs, the following changes were agreed upon because the "View" page is not what people typically want to see when clicking a team, nor does a team have typical configurable entity displays.  It is secondary at best, since it only allows you to view a team name and status, yet it's prominently featured like the main attraction, which is not useful. 

1. Make "Team Apps" be the default tab viewed when viewing a team.

2. Change the the local task text of the default entity view from "View" to "Details".

3. Ensure that when clicking the team name link from the entity collection table on `/teams`, that this  `/teams/team/apps`.

**Comment by mxr576** [comment]
I would rather make it configurable which is the default local task then hard-code it to the "Team apps" just like it is hard-coded to "View" now.

Yes, on a vanilla installation there it not too much information that we could display about a team and that bothers me as well. Although Team entities, just like other Apigee Edge entities, are fieldable. So anybody could easily add additional (required) fields to teams (like description, reference to the team lead, contacts, etc.) If this happens the View (Details) page could become something that an end user would like to see first instead of team apps. 

We used _View_ as local task title because this is the default label of the "view entity operation" in Drupal and we wanted to be consistent in the module. We expected that if someone does not like this, it will change this in a theme (front-end side). I am not completely against to changing this to _Details_ which kinda makes more sense, I am just explaining why we tried to keep everything simple in the module.
