### ISSUE TITLE
Apigee Edge + Headless Drupal 8 + Angular

### ISSUE THREAD

**Issue by mohit-wadhwa** [apigee/apigee-edge-drupal#236]
Can we use Apigee Edge (devportal) with Drupal 8 and Angular JS as frontend ? 
Is there anything like this we can use ?

**Comment by mxr576** [comment]
Hi @mohit-wadhwa.
I am not aware of any existing implementations like this. Technically it should be possible. If you would like to keep using all advanced functionalities provided by the Apigee Edge module (credential management, access control, caching, entity API, etc.) but replace the front-end with an Angular/React/Vuejs app then you could expose API endpoints for Apigee Edge entities in Drupal with the JsonAPI module for example. You will need some core and contrib patches for this:
* https://www.drupal.org/project/drupal/issues/3042467
* https://www.drupal.org/project/jsonapi_extras/issues/3044492

If you would like to truly leverage the performance benefit of the decoupled front-end you should consider a fully-decoupled solution without the Apigee Edge module because it can only perform [synchronous communication with the Apigee Edge](https://github.com/apigee/apigee-client-php/issues/7) at this moment. Although, with a decoupled front-end you could (and probably should) send async API calls to Apigee Edge. Of course, this type of implementation also has its drawbacks, like that you have to build everything from scratch and you have secure communication between the front-end and Apigee Edge.

I hope this helps.

**Comment by cnovak** [comment]
I don't know of anyone doing this yet, and like @mxr576 said you should be able to do this.  There is a lot of info out there about [Drupal 8 running headless](https://dri.es/how-to-decouple-drupal-in-2019) including a [book about it](https://www.apress.com/gp/book/9781484240717).  

If you find anything missing in this module that prevents you from implementing this solution let us know.

**Comment by mohit-wadhwa** [comment]
Thank you @mxr576 and @cnovak for your comments. Appreciate your time !!
