### ISSUE TITLE
Integration with Drupal Views

### ISSUE THREAD

**Issue by vaibhavjain-in** [apigee/apigee-edge-drupal#239]
**Is your feature request related to a problem? Please describe.**
I am trying to create a view, with apps as entities. I see apps are entities, but they are not exposed to Views.

**Describe the solution you'd like**
Integrate custom entity with Drupal Views.

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by mxr576** [comment]
Hi,

TL;DR; Views module not supported yet and maybe won't be anytime soon,

I have spent a small effort in an earlier phase of this project to investigate this topic and this is what I concluded: Views in Drupal 8 is still only working with MYSQL compliant database engines and not entities. Views still run SQL like queries on the exposed database tables and not entity queries on exposed entities. The Apigee Edge integration does not expose the Apigee Edge API as a database to Drupal, therefore, it is not possible to use it with Views.

**Comment by kscheirer** [comment]
I have a couple of questions on this topic:

1. Is this related to the "edge entities are neither content nor config entities"?
2. Why can't they be content entities?
3. Edge entities are still stored in Drupal's cache table? What are the drawbacks of storing them as real entities in Drupal's DB?
4. Will other contrib modules be able to work with Edge entities?
5. What about something like https://www.drupal.org/project/efq_views?

**Comment by mxr576** [comment]
(Sorry, I'll give you only short answers because this topic is much broader than you would expect. :)) 

1. No.
2. Well, it's like asking why a motorcycle is not a bicycle :) Content entities come with a bunch of OOTB features that Apigee Edge itself does not support, for example, revisioning. Fieldability is also not supported by all Apigee entities either, but we still managed to implement it if it could be supported without subclassing ContentEntityBase.
3. (1) Yes, but data is sanitized, ex.: API keys are not cached. (2) GDPR/data security + the two systems could get quickly out of sync. Compared with regular Drupal entities that you do not just start modifying in their actual data storage, in the database, Apigee entities could be rightfully modified via API calls or on the MGMT/MINT UI anytime. The problem that Drupal could not be notified about these changes because webhooks still does not exist in Apigee and maybe they never will.
4. Yes, they ~will~ can. Especially if they do not assume that [every entity in Drupal core is either content- or config](https://www.drupal.org/project/issues/search?issue_tags=not%20every%20entity%20is%20content%20or%20config). =]
5. As you could see, it is Drupal 7 only and it never got a stable release. It was an exciting initiative, but it never succeeded.

**Comment by kscheirer** [comment]
@mxr576 Thanks for the detailed response!

I'd like to expand on (3) and caching. I'm making a lot of assumptions here, please let me know if I'm wrong! 

- Sanitization would still be possible, you could still remove API keys from the API call result before storing.
- [removed comment about GDPR, I dont think it applies here since the data is stored in Drupal's database either way]
- Data Security/Sync - I'm not seeing any benefit here. With the current implementation the Edge object could be modified via API calls as well. Drupal will not be notified. So we have some concept of cache refresh and invalidation, whether you use the cache_* tables or entity/field tables.

Since ApigeeEdge is a base class for all the D8 apigee entities - none of them can be used with Views currently. This affects Developer Apps, Teams, Team Apps, API Products, and probably the monetization entities like rate plans and packages.

So options for resolution are:
- hook_views_data() to expose either the cache table or Apigee Edge API
- Integrate Views with EFQ
- Allow Edge entities to use mysql storage
