### ISSUE TITLE
Register new users even without connection to Apigee Edge

### ISSUE THREAD

**Issue by joaoclobocar** [apigee/apigee-edge-drupal#240]
Receiving the message: Could not create/update Drupal user: user@fqdn, because there was no connection to Apigee Edge.

Doesn't make sense to have users registered even without connection to Apigee Edge?

**Comment by kscheirer** [comment]
Moving to apigee-edge-drupal project, which is where I think this requirement is being enforced.

**Comment by mxr576** [comment]
Extending what @arunz6161 wrote, this behavior also ensures that the two system 99% times is sync, which means no Drupal user could exists without an account on Apigee Edge. If a Drupal user do not have an account in Apigee Edge it gets a "communication error" or something like that error page everytime when it visits an Apigee Edge related page in Drupal.

**Comment by joaoclobocar** [comment]
I think people from marketing or blog team also can be a user to Drupal portal.
For doing tasks not related to API´s they don´t need to have an account in Apigee Edge.

**Comment by mxr576** [comment]
Well that is true, it is a valid use case. But the API catalog provided by Apigee [depends]( https://github.com/apigee/apigee-api-catalog-drupal/blob/8.x-1.x/composer.json#L8 ) on the Apigee Edge module, because the covered use case is different. Even if you are a marketing or a blog team user on the site, you could obtain and use API keys on the developer portal. For example, if you are only uploading API documentations you could still try them out with a sandbox API and for that you need a key. The possibility is there and because of that it is simpler to ensure that meanwhile the registration process a developer account is also created on Apigee Edge.

If you are looking for less coupled solution, check Pronovix's solution which only provides a generic API documentation/developer portal functionality and in addition, if it is required, it provides an integration with Apigee Edge by using this module: https://www.drupal.org/project/devportal

**Comment by joaoclobocar** [comment]
I understand, API catalog is full coupled to Apigee Edge.
It is not a problem having an account on Apigee Edge for users others than developers.
Thank you for the good explanation.
