### ISSUE TITLE
Unable sync developers from SSO enabled apigee edge to drupal 8

### ISSUE THREAD

**Issue by rengan76** [apigee/apigee-edge-drupal#253]
After OAuth connection successful and got the OAuth.dat token. When try to click on the APPS button errors and when try to sync developers below is the error

An AJAX HTTP error occurred.
HTTP Result Code: 200
Debugging information follows.
Path: /batch?id=5&op=do_nojs&op=do
StatusText: OK
ResponseText:

I have tried to remove db and created db 10 times. our Org is enabled with SSO apigee edge. I have tested with my evaluation APIgee edge its working fine. Whenever try to connect with SSO apigee edge connection it says connection sucessful but no luck.

**Comment by mxr576** [comment]
I guess it is related to the fix in the #247 PR that has been released yet. Try to enable the Apigee Edge: Debug module as a temporary fix.

**Comment by rengan76** [comment]
TypeError: Return value of Drupal\apigee_edge\Entity\Controller\Cache\DeveloperIdCache::getEntityId() must be of the type string, null returned in Drupal\apigee_edge\Entity\Controller\Cache\DeveloperIdCache->getEntityId() (line 40 of C:\xampp\htdocs\portal\web\modules\contrib\apigee_edge\src\Entity\Controller\Cache\DeveloperIdCache.php) #0 C:\xampp\htdocs\portal\web\modules\contrib\apigee_edge\src\Entity\Controller\Cache\EntityIdCache.php(74): Drupal\apigee_edge\Entity\Controller\Cache\DeveloperIdCache->getEntityId(Object(Apigee\Edge\Api\Management\Entity\Developer)) #1 [internal function]: Drupal\apigee_edge\Entity\Controller\Cache\EntityIdCache->Drupal\apigee_edge\Entity\Controller\Cache{closure}(Object(Apigee\Edge\Api\Management\Entity\Developer)) #2 C:\xampp\htdocs\portal\web\modules\contrib\apigee_edge\src\Entity\Controller\Cache\EntityIdCache.php(73): array_map(Object(Closure), Array) #3 C:\xampp\htdocs\portal\web\modules\contrib\apigee_edge\src\Entity\Controller\Cache\EntityCache.php(94): Drupal\apigee_edge\Entity\Controller\Cache\EntityIdCache->saveEntities(Array) #4

**Comment by rengan76** [comment]
<img width="817" alt="backenderror" src="https://user-images.githubusercontent.com/4405193/62879904-20d22680-bcfa-11e9-9b60-3664d6982f95.PNG">

**Comment by rengan76** [comment]
<img width="811" alt="oauthtoken" src="https://user-images.githubusercontent.com/4405193/62879917-27609e00-bcfa-11e9-992e-96bc018971c1.PNG">

**Comment by arunz6161** [comment]
@rengan76 i noticed the configuration information you shared, thanks for that. There are a couple of issues i noticed:

1. Apigee Edge Endpoint - Please leave this blank as you are pointing to an org on edge / cloud. Leaving it blank will cause is to pick the default "https://api.enterprise.apigee.com/v1" which is the right value in your case.

2. Authorization Server- Please change this to "https://{zonename}.login.apigee.com/oauth/token", right now you have "edge" instead of "oauth/token".

Please make these changes and let us know if that helps resolve the issue. We are looking in to the issue further to prevent such misconfigurations and will update the thread with a detailed plan.

**Comment by rengan76** [comment]
Hi Arrun:

I have tried that also it always gives me bad credentials

Failed to connect to the OAuth authorization server. The given
username (*XXXXX@xx.com
<XXXXX@xx.com>*) or password or client ID (*devportaladmin*) or client
secret is incorrect. Error message:
*{"error":"unauthorized","error_description":"Bad
credentials"}*

-Ranga

**Comment by rengan76** [comment]
This needs to have proper documentation and proper testing. Only evaluation apigee edge connection is working for me with drupal 8 i can see the apps and sync developers. When i try with SSO enabled apigee edge. always something or other. Someone need to give a patch and test i properly

**Comment by rengan76** [comment]
Also when the connection sucessful only it will create this file apigee_edge_connection_default on .agigee_edge folder. When i sync developers it will create a oauth token as .dat file. endpoint leaving blank sometimes endup with host cannot be empty.

**Comment by arunz6161** [comment]
@rengan76 I just noticed that on point 2 of my previous response there was a typo- the setting should be "https://**{zonename}.**login.apigee.com/oauth/token" .Please make sure that you have this set correctly.

We will soon reach out to you via the ticket to take this further. Apologies for the issues you have been facing so far.

**Comment by rengan76** [comment]
yes i have tried that also several times. It works everything with postman. when i try with drupal 8 this is not working.

**Comment by arunz6161** [comment]
@rengan76 thanks for your patience as we worked this through on the support ticket. We found that "devadmin" user created with Developer Administrator role had run in to a bug. Once this was corrected, you were able to get the edge connection settings configured successfully and were able to run developer sync. While the root cause here was the faulty "devadmin" user, we also recognized some improvements we can do at the portal side to bring more clarity and i have captured them on #254 , please feel free to add your feedback there.
