### ISSUE TITLE
Stop using "First Name" "Last Name" as default values

### ISSUE THREAD

**Issue by cnovak** [apigee/apigee-edge-drupal#279]
* The UID 1 user is always "Firstname" "Lastname", change that to be something better.
* Stop using "Firstname" "Lastname", but instead use username so that the name is clear when displayed. User can always edit to fix the name.
* We could use username in both fields, or if the username has a dot in it, split by that dot. For example, `jon.doe` can be Firstname: `Jon`, Lastname: `Doe`.  Not perfect, but keeps us from having all kinds of "firstname lastname" accounts.

We should test:
1. New install, UID 1 
2. What happens when there are 1 or more new accounts in Drupal but not in Edge and the Apigee Edge module gets installed?

_Originally posted by @kscheirer in https://github.com/apigee/apigee-edge-drupal/issues/276#issuecomment-538511701_

**Comment by minnur** [comment]
@cnovak see https://github.com/apigee/apigee-edge-drupal/issues/280

**Comment by mxr576** [comment]
> The UID 1 user is always "Firstname" "Lastname", change that to be something better.

This is something that you can easily solve in the Kickstarter, you just need to expose the First Name and Last name fields in an install profile step.

 > Stop using "Firstname" "Lastname", but instead use username so that the name is clear when displayed. User can always edit to fix the name.
See my suggestions here: https://github.com/apigee/apigee-edge-drupal/issues/280#issuecomment-547898262


New installations, created from the Kickstarter are the simplest because from the beginning you can enforce newly created users to fill in the First name and last name fields. (UID1 can also set this, see my suggestions above.)
The actual problem is existing Drupal installations with existing users (ex.: 10k or more). If you install the Apigee Edge module on those, when the module install happens, there is no way to run a batch and initialize all users' first name and last name fields. Although those fields must be set, otherwise users can not be sync with Apigee Edge. Using the base field is a handy solution for this problem because it just provides a default value for these fields. There is no need to run any batch update on the users before you could create developer accounts for them on Apigee Edge - which is required because otherwise, they cannot access any app-related pages in Drupal.

**Comment by trebde** [comment]
Hi not sure where to leave this comment so just gonna leave it here....

We are trying to update to 8.8.0 and I'm just wondering if you are planning on releasing 8.x-1.4 within the next week? If not we can patch it for now but if you are planning on releasing soon I may hold off and just wait for the update. 

Thanks for all you hard work everyone!

**Comment by cnovak** [comment]
Moved @trebde comment to new issue #316

**Comment by cnovak** [comment]
Closing as duplicate of #307 to reduce confusion
