### ISSUE TITLE
Master plan for "username" / "firstname", "lastname" issues

### ISSUE THREAD

**Issue by arunz6161** [apigee/apigee-edge-drupal#307]

**Comment by cnovak** [comment]
# Overview
There are two "First Name", "Last Name" issues in apigee-edge:
* #280: Stop changing username to "Firstname Lastname"
* #279: Stop using "First Name" "Last Name" as default values
* [apigee-devportal-kickstart-drupal #270](https://github.com/apigee/apigee-devportal-kickstart-drupal/issues/270): Kickstart profile hides actual username, hard to connect to REST API

Along with PRs that are still open around these tickets:
* #288: Allow disabling username override w/ first name + last name 
* [apigee-devportal-kickstart-drupal #274](https://github.com/apigee/apigee-devportal-kickstart-drupal/pull/274):  Show the username on the user profile page 

# Problem Revisited
The issues above are trying to solve the problem that the Apigee Edge module changes the default display to show "Firstname" and "Lastname" instead of username where username is used. This shows up in the logs, the user profile, and list of users.

Before installing Apigee Edge module, the username is properly displayed in list of people and on user profile:
<img width="564" alt="Screen Shot 2020-03-11 at 1 19 55 PM" src="https://user-images.githubusercontent.com/613093/76460427-3811e900-639b-11ea-89f9-269be6902d70.png">
<img width="394" alt="Screen Shot 2020-03-11 at 1 20 02 PM" src="https://user-images.githubusercontent.com/613093/76460433-3ba57000-639b-11ea-9a3c-4ad515f6de78.png">

After installing Apigee Edge, those same pages look like this:
<img width="429" alt="Screen Shot 2020-03-11 at 1 22 47 PM" src="https://user-images.githubusercontent.com/613093/76460586-80c9a200-639b-11ea-926e-736cdf844b59.png">
<img width="415" alt="Screen Shot 2020-03-11 at 1 22 56 PM" src="https://user-images.githubusercontent.com/613093/76460589-82936580-639b-11ea-9065-3eb296183600.png">

This causes the following problems:
1.  username not displayed in user field, hard to connect to REST API
: [apigee-devportal-kickstart-drupal #270](https://github.com/apigee/apigee-devportal-kickstart-drupal/issues/270)
2. Username becomes the string "Firstname Lastname" for all users created before Apigee Edge module is installed, as seen above
3. Log files show "Firstname Lastname" for users in log messages
4. When installing, the first user is always installed before Apigee Edge module, which means that the user will display as "Firstname Lastname" everywhere which looks odd.

# Solution
Approve https://github.com/apigee/apigee-devportal-kickstart-drupal/pull/274 so that Kickstart shows the username again on the profile page.

Create a PR to remove `apigee_edge_user_format_name_alter` so that Apigee Edge no longer changes username field to display "Firstname Lastname", as @arlina-espinoza pointed out in [apigee-edge-drupal #281](https://github.com/apigee/apigee-edge-drupal/pull/281#pullrequestreview-304117418) that this function is
> presentation logic that is not related to this module and is just making things confusing.

We can add in release notes to explain how users can change back that functionality in a custom module if they choose to keep it.

The issue with the  "Firstname Lastname" showing up for users will be handled automatically because we are showing the username again for username fields, instead of the Apigee introduced Firstname and Lastname fields.

**Comment by arlina-espinoza** [comment]
All looks good to me. Added a comment for the release notes on PR#359: https://github.com/apigee/apigee-edge-drupal/pull/359#pullrequestreview-375439785
