### ISSUE TITLE
First Name and Last Name TypeError: Argument 1 passed to Drupal\apigee_edge\Entity\Developer::setFirstName() must be of the type string, null given

### ISSUE THREAD

**Issue by ganesh-k4** [apigee/apigee-edge-drupal#417]
## Description
We are still seeing the First Name Last Name error come up. This time it happened on prod with the user 
## Steps to Reproduce
1. Go to 'Simplesaml Login'
2. Click on 'Enter to login'

## Actual Behavior
If login with the simple saml if null string in the first name and Last name is showing the below error.
The website encountered an unexpected error. Please try again later.
TypeError: Argument 1 passed to Drupal\apigee_edge\Entity\Developer::setFirstName() must be of the type string, null given, called in /home/site/wwwroot/modules/contrib/apigee_edge/src/UserDeveloperConverter.php on line 107 in Drupal\apigee_edge\Entity\Developer->setFirstName() (line 375 of modules/contrib/apigee_edge/src/Entity/Developer.php).
## Expected Behavior
If null string in the first name last name need to add default first name and Last name in the base field of first name and Last name. so check the module and added the condition of the base field Value is not NULL.

## Notes
https://www.drupal.org/project/apigee_edge
Added patch in the below reference module to fix the issues and need to add the patch in the upcoming version.
![userdevelopercoverter php_file](https://user-images.githubusercontent.com/66430365/83778022-c13d7100-a6a7-11ea-81ca-e0312371c2a9.PNG)

## Version Info
https://www.drupal.org/project/apigee_edge
8.x-1.10 Stable release covered by the Drupal Security Team released 13 May 2020

**Comment by mxr576** [comment]
Ahh, yes SimpleSaml PHP modules always requires a custom care, not just because you have to set the property mapping. It tries to create _stub_ users with incomplete profile data and because of that, mandatory fields can be null when the user and the developer is being created. It does not even call `$user->validate()` when it saves the stub. :( The referenced PR is definitely a no go because it is an incorrect workaround for the problem.

You should hook into to the Simple SAML user creation flow and disable the Apigee Edge developer creation when the SAML module only tries to create a stub user.

**Comment by mxr576** [comment]
Based on the patch you submitted as a fix, I also have a question: did you setup a mapping for the first name and last name fields for users who come from the IDP? Because it seems to me you may not.

**Comment by ganesh-k4** [comment]
> Based on the patch you submitted as a fix, I also have a question: did you setup a mapping for the first name and last name fields for users who come from the IDP? Because it seems to me you may not.

Hi mxr576

Yes mapped the first name and last name fields in the configuration end. 
Since not sure, why the error comes up?  if is the string NULL in the particular module. is supposed to be fixed right.

**Comment by arlina-espinoza** [comment]
Thanks for the PR @ganesh-k4 . I agree wtih @mxr576 in this too. The base fields added by this module are set as required, so if another module is conflicting it would be because it's not respecting validation. The workaround suggested by @mxr576 could work by disabling the apigee_edge developer sync while the user is only a stub. You can disable the sync with:

```
_apigee_edge_set_sync_in_progress(TRUE);
```
And be sure to re enable it after:
```
_apigee_edge_set_sync_in_progress(FALSE);
```
In the worst case scenario, custom code could be added to create the developer after the required fields have been synced from SAML in another hook/event, with:

```
apigee_edge_user_presave($account);
```

**Comment by cnovak** [comment]
Will close, but let us know if https://github.com/apigee/apigee-edge-drupal/issues/417#issuecomment-643942367 does not help
