### ISSUE TITLE
Status of the App is not updated immediately on the App list

### ISSUE THREAD

**Issue by csisztaiarnold** [apigee/apigee-edge-drupal#430]
## Description
When someone logs in as an authenticated user (not admin) into a site, and changes the status of an App's product in Apigee Edge's UI, the status will not change on the App list as well. Meanwhile, it's refreshed on the App's page itself.
This might be confusing for a user.
For a user who is logged in to the site as an administrator, this works as intended.
None of the cache settings (API Product caching or Developer App settings cache) affects the outcome. 

## Steps to Reproduce
1. Create an App in Drupal, append a Product and a User to it.
2. Log in to the site with the corresponding user and go to the App list.
3. In Apigee Edge's UI, change any Product's status of the App (from Approved to Revoked or vice versa).
4. Refresh the App list page.

## Actual Behavior
The status in the App list remains unchanged, whilst if you click on the App's name and go to the App page itself, the status is changed. The status on the App list will only change if a global cache rebuild is applied.

## Expected Behavior
Change the status of the App on the App list as well.

## Screenshots
On the App list: https://i.imgur.com/ndKIA69.png (status is not changed)
On the App's page: https://i.imgur.com/mmpWq5A.png (status is changed)

## Version Info
Apigee Edge Drupal integration Module 8.x-1.7, Drupal core 8.8.6

**Comment by mxr576** [comment]
Drupal does not handle if an entity can be edited outside of Drupal's database. Also, it seems entity list builders were being built for admin purposes and not for end-users. When an entity gets updated in Drupal, the  `[ENTITY_TYPE]_list` tag automatically gets invalidated in caches, which invalidates cached entity list builder pages.

This is not enough here. We have an app cache that controls how long we should not ask Apigee Edge for changes basically. This is basically a cache max age for all places where an app is being rendered and it works on the app view, but not on the list pages, because Drupal's entity listing pages does not calculate with cache data related to listed entities.

We have a calculated "App state" rendered on the list builder and the render array should contain all cache data from the related app entity, including max-age.

My guess that this could be an issue on other entity listing pages, not just on apps.

A simple fix could be added the configured cache timeout to entity listing pages too.

**Comment by arlina-espinoza** [comment]
Yeah, I also think that potentially all list builders might not be respecting the cache expiring time set in their respective apigee settings, not just for apps. We could add a `max-age` cache tag to the listing render array to enforce the cache settings, besides the `[ENTITY_TYPE]_list` tag . We did similar work for the team lists in this PR: https://github.com/apigee/apigee-edge-drupal/pull/419

**Comment by shadcn** [comment]
@arlina-espinoza Are we adding the `max-age` to all entity list builders or apps only? AFAIK we don't have a global `max-age` config.

**Comment by arlina-espinoza** [comment]
@arshad Lets add it to the developer apps and team apps. Teams also have separate caching options but those should have been fixed in #419 already, and developers also have custom cache settings, but there isn't a list builder for them, so we should be good fixing these two.
