### ISSUE TITLE
Apigee Edge module 8.x-1.12 disabled autocomplete feature on the "add team member"

### ISSUE THREAD

**Issue by kthotti** [apigee/apigee-edge-drupal#452]
**Is your feature request related to a problem? Please describe.**
The new version, Apigee Edge module 8.x-1.12, replaced the email autocomplete field on the "add team member" form with a text field that accepts comma separated emails, to avoid displaying email addresses of users of the system.
The autocomplete feature was very useful for the team owner as it is difficult to have the email addresses handy

**Describe the solution you'd like**
What is the alternative for the Team owner to find users in the system? The team owner may not have access to users' info in the portal. 

**Additional context**
Since portal admin or team admin can add team members, why is the auto-complete considered as security vulnerability?
With new feature team members should know the valid email address user signed up

**Comment by kscheirer** [comment]
"Team" is a very flexible concept, sometimes its used in a way where displaying those email addresses is considered a vulnerability. In your setup this does not seem to be the case. 

Maybe this can be configurable? A user permission like `use autocomplete (display all user emails)` or just a configurable option the portal admin can set.

**Comment by varuntit101** [comment]
Hi @kscheirer making it configurable might be a good option.

**Comment by arunz6161** [comment]
@kthotti @kscheirer @varuntit101 - We removed the autocomplete option due to the security issue described here : https://www.drupal.org/sa-contrib-2020-028 . In short, showing list of all portals users would not be an option here due to security concerns. An alternate could be to allow for autocomplete for users who have the same email domain as you. Could you please log a feature request if that is something you will find useful.
