### ISSUE TITLE
Provide more comprehensive logging for apps and teams

### ISSUE THREAD

**Issue by VladimirAus** [apigee/apigee-edge-drupal#493]
Currently, no logging and auditing is done apart from errors.

# Proposal

* to log every app action
* to log every team action
* provide ability to switch off comprehensive logging from administration pages

**Comment by arlina-espinoza** [comment]
Perhaps the admin setting to decide on the level of logging could go under `/admin/config/apigee-edge/error-page-settings`, but renaming the page to be "Logging and error handling".

**Comment by minnur** [comment]
I can see several options where we could add configuration for logs.

1. One global setting "comprehensive logging" and each module would just use that as a flag wether to log every action or not. We could make the change just like Arlina suggested in the previous comment and rename the page and change its URL to something like `Logging and error handling` /admin/config/apigee-edge/loggin-error-handling
2. Since Teams is a submodule I think it makes sense to have a Logging tab on the Teams settings page and the same for the Apps.

**Comment by cnovak** [comment]
I am thinking that @arlina-espinoza 's idea may be a good one. If I am using these modules, it may be frustrating to try to figure out which logging I need to turn on, and turning all on/all off would be a pain if they were separate.
