### ISSUE TITLE
Update Apigee connections settings information for apigee.google.com 

### ISSUE THREAD

**Issue by arunz6161** [apigee/apigee-edge-drupal#526]
Adding this card to track the work needed to update working on the Drupal Module connection page:

Modify drupal module connection settings options to say "Hybrid / TBD" or something like that

**Comment by cnovak** [comment]
@arlina-espinoza and I were talking about how this will be confusing if we do not update this soon. There are two main versions which we can call 4G and 5G.  4G is hosted at apigee.com, so if you log in to look at your org on apigee.com, you are using our 4G (4th version) product. 5G is our new version hosted at apigee.google.com.  The 5G version is also called NgSaaS and/or hybrid. The reason is that for apigee.google.com, you can either run 5G hosted completely by Apigee (NgSaaS), or you can run the Apigee Runtime in your own datacenter (Hybrid) or any cloud provider, so that the runtime is close to your APIs. Both NgSaas and Hybrid are running on our new platform at apigee.google.com, so there is no difference for API clients like Drupal, they still talk to the apigee.google.com platform since the management layer is in GCP no matter whether you are running hybrid or NgSaas. Another note is that 4G can be ran on premise, which means all of Apigee is ran in the customer's data center, including management APIs. For this option, the customer needs to let the Drupal site know where the Apigee APIs are hosted.

Here is a breakdown:
* 4G (apigee.com)
  * public cloud, all of Apigee hosted at apigee.com
  * private cloud, all of Apigee hosted at customer's data center
* 5G (apigee.google.com)
    * NgSaaS (runtime hosted by Apigee in GCP)
    * Hybrid (runtime hosted by client anywhere they want)

What we can do for now is change the wording for the radio buttons to be:

**Apigee Instance**
- On apigee.com (Endpoint: https://api.enterprise.apigee.com/v1 )
- On apigee.google.com ( Endpoint: https://apigee.googleapis.com/v1)
- On Private cloud (Custom endpoint)


The change would be here:
![image](https://user-images.githubusercontent.com/4062676/101818217-66faee00-3ad8-11eb-944a-be6b54333fa5.png)


The documentation link on the help also needs to be updated, which is issue #533

**Comment by cnovak** [comment]
Update: The naming has changed:
Apigee X is the new name for 5G and Apigee Edge is the name for 4G, so the radio buttons should be:

- Apigee Edge (Endpoint: https://api.enterprise.apigee.com/v1 )
- Apigee X ( Endpoint: https://apigee.googleapis.com/v1)
- Private cloud (Custom endpoint)

@earth2marsh @arunz6161 FYI
