### ISSUE TITLE
Adding entity reference field to team entity causing validation issue

### ISSUE THREAD

**Issue by aparnak123** [apigee/apigee-edge-drupal#561]
## Description
When we add reference field using manage fields for  team entity getting error for  validation as edit form doesn't contain complete team object with all fields.

Error: Call to a member function getValue() on null in Drupal\Core\Entity\Plugin\Validation\Constraint\ValidReferenceConstraintValidator->validate() 

## Steps to Reproduce
1. Go to  admin/config/apigee-edge/team-settings/fields
2. Add entity reference field
3. Add a team and add some values in entity reference field, save (works fine)
4. Edit team and try adding some values in entity reference field (Throws error)

## Actual Behavior

Validation error

## Expected Behavior
should pass

## Version Info
Drupal core 8.9.11
Apigee teams- 8.x-1.17

**Comment by aparnak123** [comment]
@giteshk : I don't want to remove core validation and have custom ones.

Digged in more an found in 

/core/lib/Drupal/Core/Entity/Plugin/Validation/Constraint/ValidReferenceConstraintValidator.php


$existing_entity = $this->entityTypeManager->getStorage($entity->getEntityTypeId())->loadUnchanged($entity->id());

This loads only partial team entity without fields...This is causing issue.

**Comment by raakesh-blokhra** [comment]
@aparnak123 I am looking into this, will revert back shortly. Thanks

**Comment by raakesh-blokhra** [comment]
We are still working on it. Should have a resolution in a day or so.

**Comment by shishir-intelli** [comment]
Hi @aparnak123 ,

Sorry for the late response. 
This issue seems to be Drupal core entity system issue. I will create a PR for this issue in https://github.com/apigee/apigee-devportal-kickstart-drupal.

Meantime, I will advice you to try this patch https://www.drupal.org/files/issues/2021-04-23/validate-reference-constraint-3210319-3.patch for resolving your teams edit issue.

You can add this below patch inside your composer.json file inside `extra` section, 

        "patches": {
            "drupal/core": {
                "Validation issue for entity reference field on updating teams #561": "https://www.drupal.org/files/issues/2021-04-23/validate-reference-constraint-3210319-3.patch"
            }
        }

and run `composer update` command , which will then update your `ValidReferenceConstraintValidator.php` class.

_(Better to backup you code before composer update)_
For more information about applying patch please refer https://www.drupal.org/docs/develop/git/using-git-to-contribute-to-drupal/applying-a-patch-in-a-feature-branch#s-composer

**Comment by shishir-intelli** [comment]
Hi @aparnak123 

Hope that patch worked.
Please let us know if you face any further issue.

**Comment by shishir-intelli** [comment]
Closing this ticket for now. Feel free to reopen in case you are still having any issues.
