### ISSUE TITLE
403 status code when accepting/declining invitation

### ISSUE THREAD

**Issue by yenoomluap** [apigee/apigee-edge-drupal#570]
## Description
A user cannot accept/decline a team invitation directly from email if they are not currently logged into the site.
## Steps to Reproduce

Attempt 1 - fail
User receives an invitation to join a team
User clicks the link to accept/decline the invitation received
User receives status code 403 forbidden

Attempt 2 - win
User receives an invitation to join a team
User logs into the developer site
User clicks the link to accept/decline the invitation received
User now can accept the invitation

## Actual Behavior
click link, get 403 forbidden if not currently logged into site

## Expected Behavior
click link, get redirected to sign in if not currently logged into site, sign in, accept/decline invitation to team

## Version Info
Apigee Edge 8.x-1.20

We use saml for sign in and not local accounts.

**Comment by raakesh-blokhra** [comment]
Thanks @yenoomluap 

We'll get this sorted out shortly. @phdhiren please take a look and revert back.

**Comment by yenoomluap** [comment]
@raakesh-blokhra Is reproduceable on your side - I'm not leaving out possibility it is issue on our side.

**Comment by raakesh-blokhra** [comment]
I haven't tested it yet. We are in the process of a release, so I have requested @phdhiren to check and see if it can be reproduced, and if so, resolve it, or get back to you in the next 24 hours or so.

**Comment by phdhiren** [comment]
@yenoomluap, @raakesh-blokhra,
I could replicate the issue with given steps.

Possible solution:
Instead of providing link to sign up (register) link, we should provide sign in (login) link, while we by default assume that invited member is already member.

New user registration can be different for each of the portal https://www.drupal.org/docs/user_guide/en/config-user.html#s-steps
The invite link will equally work however due to email verification flow, it may not work directly.

My suggestion would be to have invite link to map to login instead of register

**Comment by yenoomluap** [comment]
@phdhiren I see this is closed, when can we expect release?   Thank you

**Comment by yenoomluap** [comment]
@phdhiren After updating to latest 1.23 release I had thought the experience was to be if a user was not logged into the portal, they would be taken to login page, and then would be able to accept / decline?

Currently we have the same issue, clicking link from email still takes to 403 forbidden page if user is not signed in.
