### ISSUE TITLE
Event list for Developer App Entity

### ISSUE THREAD

**Issue by sarathjasrin** [apigee/apigee-edge-drupal#573]
How I can listen for the events. For example when user created a new app I want to call a external api. For create,update,delete I can listen for EntityEventTypes. 

But what if I want to listen Developer app approval process [`Key Status`].  And product approval process.

If those events available what are those name?

I'm currently using `hook_event_dispatcher` module.

**Comment by fhirfly** [comment]
I am having the same issue.  I need to register the app with another server once it's approved and cannot figure out how to get an event notification...

**Comment by shishir-intelli** [comment]
Hi @sarathjasrin 
The Apigee Edge Actions module provides support for a number of Apigee Edge-specific Events.
I believe you are looking for this Event  `apigee_edge_actions_entity_insert:developer_app` triggered after saving a new App.

For more details on Apigee Edge-specific events which are supported out of the box please check  [Apigee Edge Actions](https://www.drupal.org/docs/contributed-modules/apigee-edge/manage-reaction-rules)

**Comment by shishir-intelli** [comment]
Closing this ticket for now. Feel free to reopen in case you are still having any issues.

**Comment by sarathjasrin** [comment]
@shishir-intelli  I can listen to insert event. But I want to listen to Developer app approval process [`Key Status`]

**Comment by shishir-intelli** [comment]
Hi @sarathjasrin
Developer app approval/revoke process takes place in Apigee Edge. There is no events that are triggered when the approval for apps is initiated. The status in the devportal is updated by an API.

Currently there is no plan to add this feature, however we will definitely look into this in future. 
Closing this ticket for now. Feel free to reopen in case you are still having any issues.

**Comment by cnovak** [comment]
I understand how it would be useful to know when the app approval/revoke status changes in Edge, but if an Apigee API provider on the admin side goes into the Apigee UI admin screens and approves an app, there is no event that gets triggered from the API using webhooks or some other method. Because of this, clients of the Apigee API (in our case Drupal) has no way of knowing this event happened. 

If there was an app approval process inside of our Drupal module, we could send an event for any app status changes done in Drupal, but we expect the API Provider to use the Apigee UI to approve/deny app requests.
