### ISSUE TITLE
Disable editing user email address for logged in user 

### ISSUE THREAD

**Issue by raakesh-blokhra** [apigee/apigee-edge-drupal#587]
## Description
When a user edits their email address, it creates a new account in the backend. There has been planning done internally at b/182997472 and b/187928954 and was decided to disable the email textfield on the user edit form. This will not allow a user to change their email address in the Drupal instance.

## Steps to Reproduce
1. Go to Edit Profile
2. Change Email Address
3. Scroll down and Click on Save

## Actual Behavior
What happened after the steps to reproduce.
A new user is created in the backend and the changes are saved on Drupal.
## Expected Behavior
User shall not be able to change their email address.
## Version Info
This can be the version you can see on admin/modules in Drupal or 
the output of this command: `composer show`.  Add Drupal core and
other version information if needed.

8+

**Comment by mxr576** [comment]
> When a user edits their email address, it creates a new account in the backend. 

That must be a regression bug... it did not happen before, for sure. Is it happening on with Apigee X or everywhere ?

> There has been planning done internally at b/182997472 and b/187928954 and was decided to disable the email textfield on the user edit form. 

@cnovak WOW, that would be a **major, possibly breaking change for existing sites**, even if you go in that direction that should not happen in this major version or it has to be added as disabled by default for existing projects. (Yet, I do not see a reason why it should be enforced by default.)
Also, if you implement it, do not implement it in the form level (that I have seen in #588), it should be enforced on the entity level, because the User entity could be changed/edited programmatically or by a contrib module, like SSO integrations.

**Comment by cnovak** [comment]
Thanks for your comments @mxr576. @raakesh-blokhra should be able to give more details on what is happening here. From @mxr576 comments, we should add an issue to review #588 to enforce on the entity level. FYI @giteshk

**Comment by shishir-intelli** [comment]
@raakesh-blokhra, @giteshk 
This issue is related to https://github.com/apigee/apigee-client-php/issues/153, (https://buganizer.corp.google.com/issues/191000617)

After fix on Apigee UI https://buganizer.corp.google.com/issues/191000617#comment6, here seems to be no way to update a developer's email now for Apigee X and hybrid runtime versions `1.5.0` and `1.5.1`,  apart from this version email update (`PUT /developers`) works properly on both Apigee UI as well as on Drupal portal correctly (_so we should not disable the email field_)

Below is the error when trying to update email address on Apigee X
>     "error": {
>         "code": 400,
>         "message": "Developer update : resource name admin@example.com in the url doesnot match with the name admin123@example.com in the request payload",
>         "status": "INVALID_ARGUMENT",
>         "details": [
>             {
>                 "@type": "type.googleapis.com\/google.rpc.PreconditionFailure",
>                 "violations": [
>                     {
>                         "type": "rest.interceptor.name_mismatch",
>                         "subject": "[2002:a17:90a:4ecc::]:4103:sicbt29:9876:83195:158030369",
>                         "description": "Developer update : resource name admin@example.com in the url doesnot match with the name admin123@example.com in the request payload"
>                     }
>                 ]
>             },
>             {
>                 "@type": "type.googleapis.com\/google.rpc.RequestInfo",
>                 "requestId": "15586132339754961210"
>             }
>         ]
>     }

However, following this above error `Apigee Edge` update fails but Drupal updates the email address on Drupal portal which further creates issue when user tries to update same profile once again which creates a new user on `Apigee Edge`.

I have created PR which throws exception when Drupal encounters this error so that email address is not updated in Drupal as well.
