### ISSUE TITLE
Apigee to support multiple organisation in single Drupal instance

### ISSUE THREAD

**Issue by dhinakaran60** [apigee/apigee-edge-drupal#622]
## Description

I need to investigate the feasibility of extending the apigee_edge module to be able to support linking multiple organizations into single drupal installation.

## Steps to Reproduce

i have modified few connector controller file. i was able to switch or connect both prod and non-prod organization. i made the two credentials stored at backend .

/apigee_edge/src/SDKConnector.php

docroot/modules/contrib/apigee_edge/src/SDKConnector.php -> getCredentials() Method to used to establish the connectivity. I reuse the base method to change apigee connection Prod Vs Non-Prod org.

```
private function getCredentials(): CredentialsInterface {
    if (self::$credentials === NULL) {
      $active_key = $this->configFactory->get('apigee_edge.auth')->get('active_key');
      if (empty($active_key)) {
        throw new AuthenticationKeyException('Apigee Edge API authentication key is not set.');
      }
      if (!($key = $this->keyRepository->getKey($active_key))) {
        throw new AuthenticationKeyNotFoundException($active_key, 'Apigee Edge API authentication key not found with "@id" id.');
      }
      self::$credentials = $this->buildCredentials($key);
    }

    return self::$credentials;
  }

```

i changed to 

      **drupal_flush_all_caches();**
       $request = \Drupal::request();
       $session = $request->getSession();
       $org = $session->get('org_value');
       if ($org == 'non-prod')
      $active_key = $this->configFactory->get('apigee_edge.auth')->get('active_key');
      else
      $active_key = "apigee_edge_connection_prod";

Every thing is working fine but each change or switch i need to do the Drupal flush cache but it will be performance impact.  

is there an alternate way to flush the cache or method is available. Can you kindly help on this? 

Any general method available for clearing the apigee connection cache alone in drupal backend?

## Version Info
 8.x-1.24

**Comment by mxr576** [comment]
Supporting multiple organizations in one site is a complex task and it is not a common scenario. There are a few valid reasons for that requirement but generally speaking, if you had to separate data between orgs (eg.: due to data security requirements), you should probably do the same on the devportal side too. 

When this module (family) was built, supporting multi-org was not required (it was a wish, but never a clear must have), and based on our (Pronovix) analyses it would require a complete rewrite to properly support that feature. Basically, this is what we did for those customers that we delivered a multi-org solution. 

My recommendation is that you should not try to change this module, you should either reconsider if multi-org is a real requirement or start from scratch or contact us and we try to help you with these.

**Comment by dhinakaran60** [comment]
Hi @mxr576 ..

Thanks for the update i completely agree your statement. its not the common scenario and this is one of the requirement needed on my application

i was only expecting to support the technical notes or replacement for   **drupal_flush_all_caches();**
Since you guys are well known about the caching technique on this module implementation. 

I can manage implementing this multiple org on my own stand as per the Drupal community standard. Thanks for the support.

**Comment by dhinakaran60** [comment]
Hi @mxr576  Can you please help on this
