### ISSUE TITLE
Allow ApiProducts entities to be rendered.

### ISSUE THREAD

**Issue by Jaesin** [apigee/apigee-edge-drupal#72]
| Q                           | A
| --------------------------- | -----------------------------------------------
| Bug?                        | no
| New Feature?                | yes
| Module Version              | 8.x-1.x
| PHP Client version          | N/A
| Requires PHP client fix     | no

#### Actual Behavior

ApiProduct entities are not renderable because they are not fieldable.

#### Expected Behavior

ApiProduct entities would be renderable.

```
\Drupal::entityTypeManager()
        ->getViewBuilder('api_product')
        ->view($product)
```

#### Steps to Reproduce the behavior

Not a bug.

#### Proposed Solution

Either create a `\Drupal\apigee_edge\Entity\ViewBuilder\EdgeEntityViewBuilder` class that can handle displaying an edge entity without making it fieldable or make the ApiProduct entity fieldable so it can be rendered. The latter is probably a better solution.

**Comment by mxr576** [comment]
Indeed, ideally they should be fielable and they should support view modes where you should be able to change the visibility of base fields (properties) and custom fields (custom attribute representations) for a view mode. Also they should have a list builder - so basically they should support CRUDL in the developer portal - which would also require some additional Edge permissions from the org user used by the portal of course.

In the Drupal 7 devportal this feature has not been supported, there were no default API product listing and viewing UIs so the creation of these UIs were always a custom requirement. We focused mainly on porting default D7 devportal features to Drupal 8 - in a better way where it was possible. This is the reason why API products do not have this capability at this moment. Although, as in Drupal 7, these UIs - if they are needed - can be provided by 3rd party modules. (Listing builder can be added in `hook_entity_type_alter()` and the missing view controller can be defined in a custom module.)

Besides, based on our experiences, the majority of customers does not need these UIs, but if they do they want something really custom. So even if these UIs would exist they would be either disabled and hidden from end users or they would be overridden in custom modules.

If you opened this issue because of the Monetization integration - based on the above described reasons - I think you should/could create the listing builder and view controller for API products in the Monetization integration module, because I assume there are some Monetization (only) information that users may like to see in Drupal about API products. So even if the base apigee_edge module would/will provide these UIs for API products the Monetization (sub)module should/would override these default UIs.

@cnovak What do you think?

**Comment by Jaesin** [comment]
The goal is to make it much easier to allow customization using the Drupal provided APIs. I think the display of the entity is best handled by the module that provides the entity but if it is necessary to omit that from the entity providing module there should be only one module responsible for converting the entity to a displayable entity. That means creating a `apigee_edge_displayable_api_product` submodule that provides the view and list builders. I wonder if having that in a separate module is really justified.

The simplest implementation is adding `"view_builder" = "Drupal\apigee_edge\Entity\ViewBuilder\EdgeEntityViewBuilder",` with converts the entity to a valid render array. i.e. `['#theme' => 'api_product', '#api_product' => $entity]`. This has the limitation that you wouldn't be able to manage displays in the Drupal UI.

What would be better is to implement `FieldableEntityInterface` and use the default `\Drupal\Core\Entity\EntityViewBuilder`. Then we could allow customers to create custom view modes for products which should meet most needs.

**Comment by mxr576** [comment]
Yeah, I would not create a submodule in apigee_edge just to make API products renderable. If we would like to support displaying and listing API products (what about create/update/delete?) then it should be implemented in the core apigee_edge module and as you wrote it would be better to implement the `FieldableEntityInterface` for this.

IIRC, we haven't added support for multiple view modes because that would just cause additional complications for us. If the `default` view mode is not enough for someone then s/he can easily create a new render array/Twig template to display a customized view about an Apigee Edge entity. I am not saying that this idea should be thrown away, I am just saying first focus on adding missing UIs for API products then revisit the idea of supporting multiple view modes.

**Comment by arunz6161** [comment]
No customer has requested this yet. Closing this out, to be reopened if this is requested by the community.
