### ISSUE TITLE
Deprecation notices when running entity tests.

### ISSUE THREAD

**Issue by Jaesin** [apigee/apigee-edge-drupal#75]
| Q                           | A
| --------------------------- | -----------------------------------------------
| Module Version.                   | 1.0.0-alpha8 
| Requires PHP client fix        | no 

#### Actual Behavior

When running tests, I am getting a notice about the new `entity.memory_cache` not being included in the storage controller for Apigee entities.

```
Remaining deprecation notices (1)

  1x: The $memory_cache parameter was added in Drupal 8.6.x and will be required in 9.0.0. See https://www.drupal.org/node/2973262
    1x in RatePlanEntityKernelTest::testEntityInstantiation from Drupal\Tests\apigee_m10n\Kernel
```

#### Steps to Reproduce the behavior

I haven't tried running the edge tests lately but I imagine you would get the same error.

#### Proposed Solution

Adding the service to `\Drupal\apigee_edge\Entity\Storage\EdgeEntityStorageBase` would be the thing to do if it is going to be useful. If it's not going to be useful this issue could be the place to note why the service isn't included.

**Comment by mxr576** [comment]
I think it is fine for now, because the build-in content entities are also trigger this error in tests as I can see:
https://github.com/drupal/drupal/blob/e7862f1e060d2bc96ef2e7056b8d78e4ceabe183/core/lib/Drupal/Core/Entity/ContentEntityStorageBase.php#L59
https://github.com/drupal/drupal/blob/646584b3f718897179589f4f014531e3d9365331/core/lib/Drupal/Core/Entity/EntityStorageBase.php#L99

However I do agree that this problem should be addressed in one of the upcoming releases. I did a quick check and it seems there are some unnecessary arguments in the entity storage constructors, like the logger that we can get rid of as well.

Although it is not recommended in the long-term run, you can suppress deprecation errors with this environment variable: https://github.com/apigee/apigee-edge-drupal/blob/8.x-1.x/.travis/docker-compose.override.yml#L20 or we can use the same trick to suppress the deprecation notices by passing `\Drupal::service('entity.memory_cache');` to the parent constructor.

**Comment by mxr576** [comment]
PR #83 addresses this problem.

**Comment by mxr576** [comment]
PR merged.
