### ISSUE TITLE
Cannot ADD KEY when all Credentials are Revoked

### ISSUE THREAD

**Issue by janmashat** [apigee/apigee-edge-drupal#773]
## Description
When all Credentials/keys for a certain App have been Revoked, ADD KEY option in Drupal no longer creates new keys/Credentials.

## Apigee Info
OPDK

## Steps to Reproduce
1. Go to App Details in OPDK: /platform/{org-name}/apps/{app-uuid}
2. Click Edit and Revoke (for all credentials) and Save.
3. Go to View App in Drupal: /user/{uid}/apps/{app-name}
4. Click ADD KEY and CONFIRM

## Actual Behavior
No new key/Credential is added in Edge.

## Expected Behavior
New key/Credential should be added in Edge.

## Notes
Organization History in OPDK shows a 200 response to the UPDATE operation

## Version Info
apigee_edge 2.0.6
OPDK 4.51.00.00

**Comment by phdhiren** [comment]
@janmashat 

I could not replicate the issue, as by default one credential is always there and getting created with new app. 
Only in case of multiple credentials the revoke button is there, however if there is only one credential left then there is no option to remove that credential.

**Comment by janmashat** [comment]
@phdhiren That's strange - I have the Revoke button even for one credential.

![Screenshot 2023-01-11 at 15 38 06](https://user-images.githubusercontent.com/12157479/211836555-fcec2708-fe09-49cf-9b2a-bc7c43c9febf.png)

**Comment by phdhiren** [comment]
It seems the one you're using is using Drupal 7.
Drupal 7 dev portal is no longer supported - https://docs.apigee.com/api-platform/publish/drupal/what-developer-portal

Request you to upgrade to Drupal 9 - https://docs.apigee.com/api-platform/publish/drupal/open-source-drupal

**Comment by janmashat** [comment]
We are running Drupal 9.

The screenshot is from OPDK.

**Comment by shishir-intelli** [comment]
@giteshk @phdhiren 
To create credentials for an app at-least one product is required.
When we revoke all keys from Apigee and try to create a new key from Drupal portal, it couldn't find the API product which is why it is not creating the Key.
It tries to find API products based on the recently active API key.

IMO, we should either hide the `Add Key` button on Drupal portal when all keys are revoked or make a provision to add API products while creating a key for an app.

@janmashat Meantime, you can simply change the recently revoked key to `approved` on Apigee UI then you can create a new key in portal and revoke the older one.
![image](https://user-images.githubusercontent.com/75600200/212889400-81285d18-f311-4e4a-8002-709992cc319c.png)

**Comment by mxr576** [comment]
@shishir-intelli I have just submitted a fix and a potential follow issue for the given problem, see above your comment.

**Comment by shishir-intelli** [comment]
Thank you @mxr, 
Getting the api_product from the most recent revoked credential when all keys are revoked looks good.

I reviewed and tested the PR and it looks good to me ,  
once the test passes then I will approve it.

**Comment by mxr576** [comment]
@shishir-intelli so is it good to go? :)

**Comment by shishir-intelli** [comment]
Yes it is :)
