### ISSUE TITLE
Apigee Devportal Kickstart Drupal 9 theme

### ISSUE THREAD

**Issue by huilinks** [apigee/apigee-edge-drupal#787]
## Description
I have installed a standard Drupal 9 site with "composer create-project drupal/recommended-project my_site". The site runs fine on my localhost. 
I try to install Apigee Kickstart theme to my site, so I merged composer.json and composer.lock from https://github.com/apigee/devportal-kickstart-project-composer to my local files. Then run “composer update”. 

But I do not see “Apigee Kickstart theme” listed under /admin/appearance even though the theme’s code is in web/profiles/composer/apigee_devportal_kickstart/themes/custom/apigee_kickstart directory. 

## Apigee Info
I am using Apigee Developer Portal Kickstart.

## Steps to Reproduce
1. Run composer create-project drupal/recommended-project my_site
2. Go http://localhost:8080/my_site to install the site
3. Merge composer.json & composer.lock from https://github.com/apigee/devportal-kickstart-project-composer 
4. Run composer update, and flush cache
5. Go to http://localhost:8080/my_site/admin/appearance, Apigee Kickstart theme is not found.

## Actual Behavior
Apigee Kickstart theme is not found.

## Expected Behavior
I expect Apigee Kickstart theme is listed and can be installed.

## Version Info
Attach "composer show result"
[composer_show_output.txt](https://github.com/apigee/apigee-edge-drupal/files/10460618/composer_show_output.txt)

**Comment by huilinks** [comment]
Is there a way to download/install Apigee Kickstart theme to Drupal 9 site if the site is not installed with Apigee install profile?

**Comment by shishir-intelli** [comment]
Hi @huilinks ,

What is the reason for installing 'Apigee Kickstart theme' separately in Basic Drupal and not installing it through Drupal Apigee kickstart profile?

`Apigee Kickstart theme` is inside `Apigee Developer Portal Kickstart` Drupal distribution, you can t install it separately.
After step 2 , if you run composer update it will get the apigee_devportal_kickstart profile folder in your Drupal file structure but wont install it as you have already installed basic Drupal.

If you want to install "Apigee Developer Portal Kickstart" run 
```composer create-project apigee/devportal-kickstart-project:9.x-dev MY_PROJECT --no-interaction```  
https://www.drupal.org/node/3058326#s-installation-instructions.

and to create a Apigee sub-theme, you require Radix theme and Apigee Drupal theme.
Ref : https://github.com/apigee/apigee-devportal-kickstart-drupal/blob/6dd58a1e93e9d06536b2c79313a93b863610b0e7/themes/custom/apigee_kickstart/README.md#using-drush-to-generate-your-sub-theme:~:text=Creating%20an%20Apigee-,Kickstart,-Sub%2Dtheme

**Comment by huilinks** [comment]
I started with basic Drupal profile install, configured, set up user groups, contents etc. on my site. Later came across Drupal Apigee kickstart install profile. I do not want to delete my site with all the configs, settings, contents, then reinstall with Apigee Developer Portal Kickstart Drupal distribution. Is there a way to add Apigee theme to an existing standard Drupal 9 site?

Thanks

**Comment by shishir-intelli** [comment]
Yes, you can add it manually, however there are a lot of dependencies which might break or distort the site which you need to  handle.
Although we don't recommend doing it manually, if you need to do this then follow these steps:
1. Install `radix` theme, if you don't have it already. (_composer require drupal/radix_)
2. Install the components module.(_composer require drupal/components_)
3. Enable the components module. (_drush pm:enable components_)
4. Then, get the complete `apigee_kickstart` theme folder from `web/profiles/contrib/apigee_devportal_kickstart/themes/custom/` and paste it in `web/themes/custom/`.
5. Make sure to clear all the cache. 
6. Now, when you can see `Radix` and `Apigee Kickstart` under `/admin/appearance`, install `Radix` theme and `Apigee Kickstart` theme.

Note: because `block.block.apigee_kickstart_title` has the dependency of `apigee_kickstart_enhancement` module which is there inside Apigee Drupal profile and you have chosen to install basic Drupal and not Kickstart, So you will get missing dependency error while installing Apigee Kickstart theme.
In that case, delete the 'block.block.apigee_kickstart_title.yml' file, then clear the cache. 
Install and make the default theme `Apigee Kickstart theme`, you are done.

**Comment by huilinks** [comment]
Hi Shishir,

After deleting the 'block.block.apigee_kickstart_title.yml' file, Apigee
theme is installed on my site. Will my site miss any Apigee theme feature
without "block.block.apigee_kickstart_title"?

Thanks

**Comment by shishir-intelli** [comment]
It is basically a predefined block for generic page title that too with dependency of `apigee_kickstart_enhancement` module, if you are not using `apigee_kickstart_enhancement` module then anyway it is not useful and wont impact the site.

However, we always recommend installing the `Apigee Devportal Kickstart` to get a nice experience of Apigee, setting up the Apigee theme manually (_as suggested in the above comment_) can possibly have some CSS issue.

**Comment by huilinks** [comment]
I see, thanks.

**Comment by shishir-intelli** [comment]
Closing this issue for now, Feel free to re-open if you have any further queries.
