### ISSUE TITLE
Missing operation on custom entity form.

### ISSUE THREAD

**Issue by FCsongradi** [apigee/apigee-edge-drupal#793]
## Description
On the AuthenticationForm custom entity form, the operation is missing. This causes an error on the /admin/config/apigee-edge/settings page. The error happens because the operation is null and string is expected in hook_entity_prepare_form(). I've found this issue while using the ECA module. The eca_content submodule implemented hook_entity_prepare_form().

## Apigee Info
Apigee Edge

## Steps to Reproduce
1. Install the ECA  module
2. Install Apigee Edge module.
3. Go to the Apigee General settings: /admin/config/apigee-edge/settings

## Actual Behavior
An error occurred and the Apigee General settings page cannot be opened.

## Expected Behavior
Opening the Apigee General settings page without the error.

## Screenshots
![image](https://user-images.githubusercontent.com/95760042/216035711-caa1d223-c52c-4d95-bd47-82b989183e5e.png)

## Notes
I've found the operation set in routing.yml elsewhere.
example:

entity.crop_type.edit_form:
  path: '/admin/config/media/crop/manage/{crop_type}'
  defaults:
    _entity_form: 'crop_type.edit'
  requirements:
    _permission: 'administer crop types'

## Version Info
apigee_edge 2.0.6

**Comment by FCsongradi** [comment]
PR with a possible solution for the issue: #792

**Comment by mxr576** [comment]
This issue relies on the fact that AuthenticationForm is extending EntityFormBase [but not exposed as an entity form in routing](https://github.com/apigee/apigee-edge-drupal/blob/2.0.8/apigee_edge.routing.yml#L20), therefore `\Drupal\Core\Entity\HtmlEntityFormController::getFormObject()` does not do its "magic". But... since AuthenticationForm has a dual behavior, both handles create and edit process, we most probably could not even consider using `_entity_form`.
