### ISSUE TITLE
Drupal core patch changes Entity API

### ISSUE THREAD

**Issue by lekob** [apigee/apigee-edge-drupal#964]
## Description
The patch added in #931 adds two methods to EntityInterface (getOriginal and setOriginal). Classes that implement EntityInterface will need to implement these two methods or be declared as abstract.

## Steps to Reproduce
1. Make sure that in your project's root composer.json `extra.enable-patching` is set to `true`.
2. Require drupal/apigee_edge 3.0.2.
3. Make sure that the "Add a method to access the original property" patch is applied to Drupal core.
4. Require and enable an extension that has a class that implements EntityInterface (example: drupal/simple_oauth).
5. Configure and use the other extension as described in its documentation.

## Actual Behavior
PHP Fatal error.

## Expected Behavior
Updating to drupal/apigee_edge 3.0.2 should not cause other extensions to fail.

## Version Info
3.0.2

**Comment by divya-intelli** [comment]
@lekob , Thank you for notifying us. 
The patch was added for deprecations notice.
We will be soon releasing apigee_edge. The patch will be removed with PR #965.

**Comment by mxr576** [comment]
@divya-intelli Thanks for the quick reply. A 3.0.3 release today would be much appropriated because we have just realized that 3.0.1 release was broken because it called a private constructor of `\League\Period\Period` that was fixed in 3.0.2: https://github.com/apigee/apigee-edge-drupal/commit/746eb5de2e65d7cf54c3b495d00ae41b8507fd2a

So we are kinda in a situation where there is no acceptable release of Apigee Edge 3.x for D10 ;S Maybe 3.0.0... I have to double check that

**Comment by divya-intelli** [comment]
@mxr576 ,
1) For edge version 3.0.1 it is picking apigee client 3.0.2 as we have used `^` instead of `~` for apigee client in composer. Going forward for any deprecations/library updates we will be using `~` for new releases.
2) We have scheduled the release of edge version 3.0.3 on Monday.

**Comment by divya-intelli** [comment]
@lekob @mxr576 , we have released edge version 3.0.3 , this release includes PR #965.
