### ISSUE TITLE
Form save issue - General Config

### ISSUE THREAD

**Issue by kiranjyoth** [apigee/apigee-edge-drupal#98]
| Q                           | A
| --------------------------- | -----------------------------------------------
| Bug?                        | yes
| New Feature?                | no|yes
| Module Version              | beta1
| PHP Client version          | 7.1 & 7.2 
| Requires PHP client fix     | no|link to an Apigee Client PHP library issue or pull request

#### Actual Behavior

Form save didn't work, Test connection worked. Tried to visit /user/apps page gives connection unsuccessful error. 

#### Expected Behavior

Form should save credentials, and connection should be successful if credentials are correct. 

#### Steps to Reproduce the behavior

Install fresh vanilla version of Drupal 8.6.2 
Install Composer dependencies
Install apigee_edege module using composer
Enable module
Try to set config. 
After trying to test connection connection was successful, Save button is disabled. 
After trying to save form - Form save happens but all variables are reset. 
Tried to open MyApps page - says connection unsuccessful.

<img width="1036" alt="edge_connection_test" src="https://user-images.githubusercontent.com/1490213/49466846-e81a9e80-f7b5-11e8-865c-8fdf1e2964cc.png">
<img width="888" alt="config_saved" src="https://user-images.githubusercontent.com/1490213/49466849-ec46bc00-f7b5-11e8-8add-29ad830705d8.png">
<img width="1004" alt="myapps_page" src="https://user-images.githubusercontent.com/1490213/49466853-eea91600-f7b5-11e8-9885-ac75ebb26995.png">

**Comment by mxr576** [comment]
Hi @kiranjyoth!

Thanks for your bug report. I think the reported is caused by know issue at this moment. The beta1 version does not warn you if Drupal's private filesystem has not been configured before you would try to save your credentials. This is the location where your credentials gets saved by default.

Do you have [the private filesystem configured](https://www.drupal.org/docs/8/core/modules/file/overview#content-accessing-private-files) on your site?

If you do not, please configure it and try to save your credentials again.

If it does not work then please enable the Database logging module, go to `admin/reports/dblog/confirm` to clear the previously logged log entries. Try to configure the credentials again and when it fails, please create a screenshot for us from the `admin/reports/dblog`. It would be even better if you could share exact log entries reported with "apigee_edge" type.

**Comment by kiranjyoth** [comment]
@mxr576  Thanks for your reply. Once I configured private file system, it works as expected. 
Thank you!
